"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { ArrowRight, RefreshCw, GitBranch, Zap, Shield, BarChart2, CheckCircle, Play } from "lucide-react";

const STATS = [
  { value: "10×",    label: "Faster Deployments",   sub: "Automated pipelines, zero YAML"    },
  { value: "0",      label: "YAML Written",          sub: "Fully generated by QuickInfra"     },
  { value: "99.9%",  label: "Pipeline Uptime",       sub: "Self-healing CI/CD infrastructure" },
  { value: "1-click",label: "Any Environment",       sub: "Dev, staging, prod — instantly"    },
];

const PIPELINE_STAGES = [
  { id: "commit",  label: "Git Commit",    icon: GitBranch,  color: "#8b5cf6", duration: 1400 },
  { id: "build",   label: "Docker Build",  icon: Zap,        color: "#3b82f6", duration: 2000 },
  { id: "test",    label: "Auto Test",     icon: CheckCircle,color: "#10b981", duration: 1800 },
  { id: "scan",    label: "Security Scan", icon: Shield,     color: "#ef4444", duration: 1400 },
  { id: "deploy",  label: "K8s Deploy",    icon: RefreshCw,  color: "#8b5cf6", duration: 1600 },
  { id: "monitor", label: "Live Monitor",  icon: BarChart2,  color: "#06b6d4", duration: 900  },
];

const LOG_SETS = {
  commit:  [["HEAD → main · 3fa92c1d", "#67e8f9"], ["Files changed: 12, +340 −18", "#e2e8f0"], ["Pipeline triggered", "#4ade80"]],
  build:   [["docker build -t app:3fa92c", "#67e8f9"], ["Step 12/14: RUN npm run build", "#e2e8f0"], ["Image pushed to ECR", "#4ade80"]],
  test:    [["Running 142 test suites...", "#67e8f9"], ["Coverage: 94.2% (threshold 80%)", "#e2e8f0"], ["All tests passed (142/142)", "#4ade80"]],
  scan:    [["Trivy scan: 0 CRITICAL", "#4ade80"], ["SAST scan: 0 HIGH findings", "#4ade80"], ["Security gate: PASSED", "#4ade80"]],
  deploy:  [["kubectl apply -f k8s/", "#67e8f9"], ["Rollout: 3/3 replicas ready", "#e2e8f0"], ["Deployment v2.4.1 live", "#4ade80"]],
  monitor: [["Health check: 200 OK", "#4ade80"], ["Latency p99: 38ms · SLA met", "#4ade80"], ["Pipeline complete in 9m 12s", "#4ade80"]],
};

const FEATURES = [
  { icon: GitBranch,   title: "Auto-Generated Pipelines",   tag: "Zero Config",  color: "#8b5cf6", desc: "QuickInfra reads your repo and auto-generates the full pipeline — build, test, security scan, deploy. No templates to copy, no config to write." },
  { icon: Shield,      title: "Security Gates Built In",    tag: "DevSecOps",    color: "#ef4444", desc: "Every pipeline run includes SAST, container scanning, and compliance checks. Security is enforced before anything reaches production." },
  { icon: RefreshCw,   title: "Multi-Environment Deploys",  tag: "Environments", color: "#3b82f6", desc: "Dev, staging, and prod wired up out of the box. Promote builds with one click — no per-env YAML to maintain." },
  { icon: Zap,         title: "Instant Rollbacks",          tag: "Reliability",  color: "#f59e0b", desc: "One-click rollback to any previous successful deployment. Canary and blue/green strategies with zero downtime." },
  { icon: BarChart2,   title: "Pipeline Observability",     tag: "Visibility",   color: "#06b6d4", desc: "Real-time dashboards, build duration trends, failure rate tracking, and Slack/email alerts on every pipeline event." },
  { icon: CheckCircle, title: "IaC-Backed Infrastructure",  tag: "IaC",          color: "#10b981", desc: "Pipelines are backed by auto-generated Terraform. The CI/CD infra itself is versioned, reproducible, and drift-free." },
];

const HOW_IT_WORKS = [
  { step: "01", title: "Connect Your Repo",       color: "#8b5cf6", desc: "Link GitHub, GitLab, or Bitbucket. QuickInfra scans your codebase and detects stack, language, and deployment target automatically." },
  { step: "02", title: "Pipeline Auto-Generated", color: "#3b82f6", desc: "A production-grade pipeline is generated — build, test, security scan, deploy — wired to your cloud account with no config." },
  { step: "03", title: "Push and Ship",           color: "#10b981", desc: "Every push triggers the pipeline. Review runs in the QuickInfra console and approve production deploys with one click." },
  { step: "04", title: "Monitor Continuously",    color: "#06b6d4", desc: "Live deployment status, success rates, rollback history, and cost per pipeline run — all in one dashboard." },
];

const METRICS = [
  { before: "2 weeks",  after: "1 click",   label: "Pipeline setup",   color: "#8b5cf6" },
  { before: "Weekly",   after: "Daily",     label: "Deploy frequency", color: "#3b82f6" },
  { before: "Manual",   after: "Automated", label: "Security checks",  color: "#ef4444" },
  { before: "Hours",    after: "Minutes",   label: "Rollback time",    color: "#f59e0b" },
];

const TESTIMONIALS = [
  { quote: "We went from deploying once a week to multiple times a day. QuickInfra's auto-generated pipelines removed every ops bottleneck between our devs and production.", company: "SalesGarners Marketing Pvt. Ltd.", role: "IT Manager",        initial: "S", color: "#8b5cf6" },
  { quote: "The security gate caught a critical vulnerability before it reached prod. That alone saved us from a major incident — and it required zero configuration.",        company: "Netsoftmate IT Solutions",        role: "Managing Director", initial: "N", color: "#3b82f6" },
  { quote: "Zero YAML written. Our entire CI/CD infrastructure was generated, deployed, and running in under an hour. Genuinely remarkable.",                                  company: "CloudAge",                        role: "Director",          initial: "C", color: "#10b981" },
];

// ─── Widget ────────────────────────────────────────────────────────────────────

function CicdWidget() {
  const [mounted,    setMounted]    = useState(false);
  const [activeIdx,  setActiveIdx]  = useState(0);
  const [progress,   setProgress]   = useState(0);
  const [logLines,   setLogLines]   = useState([]);
  const [animId,     setAnimId]     = useState(null);
  const [doneIdxs,   setDoneIdxs]   = useState([]);
  const timersRef = useRef([]);

  const clearTimers = () => { timersRef.current.forEach((t) => { if (typeof t === "number") clearTimeout(t); else clearInterval(t); }); timersRef.current = []; };
  const addTimer = (fn, ms) => { const id = setTimeout(fn, ms); timersRef.current.push(id); return id; };

  useEffect(() => { const t = setTimeout(() => setMounted(true), 120); return () => clearTimeout(t); }, []);
  useEffect(() => () => clearTimers(), []);

  const runStage = (idx) => {
    if (idx >= PIPELINE_STAGES.length) {
      addTimer(() => { setActiveIdx(0); setDoneIdxs([]); setLogLines([]); setProgress(0); addTimer(() => runStage(0), 800); }, 2000);
      return;
    }
    const stage = PIPELINE_STAGES[idx];
    setActiveIdx(idx); setLogLines([]); setProgress(0);
    let p = 0;
    const iv = setInterval(() => { p = Math.min(p + 2, 100); setProgress(p); if (p >= 100) clearInterval(iv); }, (stage.duration / 100) * 2);
    timersRef.current.push(iv);
    const logs = LOG_SETS[stage.id] || [];
    logs.forEach(([text, color], i) => {
      addTimer(() => {
        const lid = `${idx}-${i}`;
        setAnimId(lid);
        setLogLines((prev) => [...prev, { id: lid, text, color }]);
      }, (stage.duration / (logs.length + 1)) * (i + 1));
    });
    addTimer(() => { setDoneIdxs((prev) => [...prev, idx]); runStage(idx + 1); }, stage.duration + 300);
  };

  useEffect(() => { if (mounted) addTimer(() => runStage(0), 800); }, [mounted]);

  const stage = PIPELINE_STAGES[activeIdx];

  return (
    <div style={{ height: 520, width: "100%", opacity: mounted ? 1 : 0, transform: mounted ? "translateY(0) scale(1)" : "translateY(28px) scale(0.97)", transition: "opacity 0.7s cubic-bezier(0.16,1,0.3,1), transform 0.7s cubic-bezier(0.16,1,0.3,1)", willChange: "opacity, transform" }}>
      <div className="h-full" >
        <div className="h-full flex flex-col rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-700/50 shadow-2xl shadow-violet-500/10 dark:shadow-black/50">
          {/* Header */}
          <div className="flex-shrink-0 flex items-center justify-between px-5 py-3 bg-gradient-to-r from-violet-700 to-purple-700">
            <div className="flex items-center gap-2">
              <span className="relative flex h-2 w-2"><span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-white opacity-60" /><span className="relative inline-flex rounded-full h-2 w-2 bg-white" /></span>
              <span className="text-sm font-bold text-white">CI/CD Pipeline · Running</span>
            </div>
            <span className="text-[10px] font-bold text-white/70 px-2 py-0.5 rounded-full bg-white/15 border border-white/20">main · 3fa92c1</span>
          </div>

          {/* Stage pills */}
          <div className="flex-shrink-0 flex gap-1 px-3 py-2.5 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-[#0f172a] overflow-x-auto">
            {PIPELINE_STAGES.map(({ id, label, color }, i) => {
              const isDone = doneIdxs.includes(i);
              const isAct  = activeIdx === i && !isDone;
              return (
                <div key={id} className="flex items-center gap-1 flex-shrink-0">
                  <div className="flex items-center gap-1 px-2 py-1 rounded-lg text-[9px] font-bold transition-all duration-300"
                    style={{ background: isDone || isAct ? color + "18" : "#f1f5f9", color: isDone || isAct ? color : "#94a3b8", border: `1px solid ${isDone || isAct ? color + "35" : "transparent"}` }}>
                    <span className="w-1.5 h-1.5 rounded-full" style={{ background: isDone ? color : isAct ? color : "#cbd5e1", animation: isAct ? "dashPulse 1s ease-in-out infinite" : "none" }} />
                    {label}
                  </div>
                  {i < PIPELINE_STAGES.length - 1 && <span className="text-slate-200 dark:text-slate-700 text-[9px]">›</span>}
                </div>
              );
            })}
          </div>

          {/* Progress bar */}
          <div className="flex-shrink-0 px-4 py-2.5 border-b border-slate-100 dark:border-slate-800 bg-white dark:bg-[#0d1117]">
            <div className="flex items-center justify-between mb-1.5">
              <div className="flex items-center gap-1.5"><stage.icon size={12} style={{ color: stage.color }} /><span className="text-[10px] font-extrabold" style={{ color: stage.color }}>{stage.label}</span></div>
              <span className="text-[9px] font-mono text-slate-400">{progress}%</span>
            </div>
            <div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
              <div className="h-full rounded-full transition-all duration-150" style={{ width: `${progress}%`, background: stage.color }} />
            </div>
          </div>

          {/* Log output */}
          <div className="flex-1 overflow-auto px-4 py-3 bg-[#0d1117]" style={{ fontFamily: "ui-monospace, 'JetBrains Mono', monospace" }}>
            {logLines.map(({ id, text, color }) => (
              <div key={id} className="flex items-start gap-2 mb-1.5"
                style={id === animId ? { animation: "logLineIn 0.3s cubic-bezier(0.16,1,0.3,1) forwards" } : { opacity: 1 }}>
                <span className="text-[9px] text-[#334155] w-4 text-right flex-shrink-0">{logLines.findIndex((l) => l.id === id) + 1}</span>
                <span className="text-[10.5px] leading-relaxed" style={{ color }}>{text}</span>
              </div>
            ))}
            {logLines.length === 0 && <span className="text-[10px] text-[#334155]">Waiting for output...</span>}
          </div>

          {/* Footer */}
          <div className="flex-shrink-0 border-t border-slate-100 dark:border-slate-800 px-4 py-2.5 bg-slate-50 dark:bg-[#0f172a] grid grid-cols-3 gap-2">
            {[["Stage", `${Math.min(activeIdx + 1, 6)}/6`], ["Status", doneIdxs.length === 6 ? "Complete" : "Running"], ["YAML", "0 lines"]].map(([k, v]) => (
              <div key={k} className="text-center">
                <div className="text-[9px] text-slate-400 uppercase tracking-widest">{k}</div>
                <div className="text-[11px] font-extrabold text-violet-600 dark:text-violet-400">{v}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function CicdPage() {
  const [heroVisible,  setHeroVisible]  = useState(false);
  const [statsVisible, setStatsVisible] = useState(false);
  const statsRef = useRef(null);

  useEffect(() => { const t = setTimeout(() => setHeroVisible(true), 80); return () => clearTimeout(t); }, []);
  useEffect(() => {
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setStatsVisible(true); }, { threshold: 0.2 });
    if (statsRef.current) obs.observe(statsRef.current);
    return () => obs.disconnect();
  }, []);

  return (
    <div className="bg-white dark:bg-slate-950 text-slate-900 dark:text-white">

      <section className="relative min-h-[88vh] flex items-center py-20 px-4 sm:px-6 lg:px-8 overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(#e2e8f0_1px,transparent_1px)] dark:bg-[radial-gradient(#1e293b_1px,transparent_1px)] [background-size:32px_32px] opacity-60 dark:opacity-40" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_-10%,rgba(139,92,246,0.09),transparent)] dark:bg-[radial-gradient(ellipse_80%_50%_at_50%_-10%,rgba(139,92,246,0.17),transparent)]" />
        <div className="relative max-w-7xl mx-auto w-full">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-7 border border-violet-200 dark:border-violet-500/30 bg-violet-50 dark:bg-violet-500/10"
                style={{ opacity: heroVisible ? 1 : 0, transform: heroVisible ? "translateY(0)" : "translateY(12px)", transition: "opacity 0.6s ease, transform 0.6s ease" }}>
                <RefreshCw size={11} className="text-violet-600 dark:text-violet-400" />
                <span className="text-xs font-bold tracking-widest text-violet-600 dark:text-violet-400 uppercase">CI/CD Automation</span>
              </div>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-[1.07] tracking-tight mb-6"
                style={{ opacity: heroVisible ? 1 : 0, transform: heroVisible ? "translateY(0)" : "translateY(18px)", transition: "opacity 0.65s ease 0.08s, transform 0.65s ease 0.08s" }}>
                Ship faster.<br /><span className="text-violet-600 dark:text-violet-400">Zero YAML.</span>
              </h1>
              <p className="text-base sm:text-lg text-slate-500 dark:text-slate-400 font-light leading-relaxed mb-8 max-w-xl"
                style={{ opacity: heroVisible ? 1 : 0, transform: heroVisible ? "translateY(0)" : "translateY(18px)", transition: "opacity 0.65s ease 0.16s, transform 0.65s ease 0.16s" }}>
                QuickInfra auto-generates your entire CI/CD pipeline — build, test, security scan, deploy — with a single click. No templates. No config files. No ops tickets.
              </p>
              <div className="flex flex-wrap gap-3 mb-10"
                style={{ opacity: heroVisible ? 1 : 0, transform: heroVisible ? "translateY(0)" : "translateY(18px)", transition: "opacity 0.65s ease 0.24s, transform 0.65s ease 0.24s" }}>
                <Link href="https://console.quickinfra.cloud/" className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold bg-violet-600 hover:bg-violet-500 text-white shadow-lg shadow-violet-600/25 transition-all hover:-translate-y-0.5">Start Free Trial <ArrowRight size={15} /></Link>
              </div>
              <div className="flex flex-wrap gap-6" style={{ opacity: heroVisible ? 1 : 0, transition: "opacity 0.65s ease 0.32s" }}>
                {[["10×", "Faster deployments"], ["0", "YAML written"], ["1-click", "Any environment"]].map(([v, l]) => (
                  <div key={l}><div className="text-sm font-extrabold text-violet-600 dark:text-violet-400">{v}</div><div className="text-xs text-slate-400 mt-0.5">{l}</div></div>
                ))}
              </div>
            </div>
            <CicdWidget />
          </div>
        </div>
      </section>

      <section ref={statsRef} className="py-14 px-4 sm:px-6 lg:px-8 border-y border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/40">
        <div className="max-w-7xl mx-auto grid grid-cols-2 lg:grid-cols-4 gap-5">
          {STATS.map((s) => (
            <div key={s.label} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 text-center hover:-translate-y-1 transition-all hover:shadow-lg">
              <div className={`text-4xl font-extrabold tracking-tight mb-2 transition-colors duration-700 ${statsVisible ? "text-violet-600 dark:text-violet-400" : "text-slate-200 dark:text-slate-800"}`}>{s.value}</div>
              <div className="font-bold text-sm mb-1">{s.label}</div>
              <div className="text-xs text-slate-400 font-light">{s.sub}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="py-20 sm:py-28 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-[10px] font-bold tracking-widest uppercase text-violet-600 dark:text-violet-400 mb-3">Capabilities</p>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4">Everything CI/CD Needs</h2>
            <p className="text-base text-slate-500 dark:text-slate-400 font-light max-w-lg mx-auto">Six capabilities that make QuickInfra the last pipeline tool you'll ever set up.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {FEATURES.map(({ icon: Icon, title, tag, color, desc }) => (
              <div key={title} className="group rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 sm:p-7 hover:-translate-y-1 transition-all hover:shadow-lg cursor-default">
                <div className="flex items-center gap-3 mb-5">
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: color + "15", color, border: `1.5px solid ${color}30` }}><Icon size={18} /></div>
                  <span className="text-[10px] font-extrabold tracking-widest uppercase text-slate-400">{tag}</span>
                </div>
                <h3 className="text-sm font-extrabold mb-2.5 leading-snug group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">{title}</h3>
                <p className="text-sm text-slate-500 dark:text-slate-400 font-light leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 px-4 sm:px-6 lg:px-8 border-y border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/40">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10"><p className="text-[10px] font-bold tracking-widest uppercase text-violet-600 dark:text-violet-400 mb-3">Real Impact</p><h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight">Before vs After</h2></div>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {METRICS.map(({ before, after, label, color }) => (
              <div key={label} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 text-center">
                <div className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 mb-3">{label}</div>
                <div className="flex items-center justify-center gap-2 mb-1"><span className="text-sm font-bold text-red-400 line-through">{before}</span><span className="text-slate-300 dark:text-slate-700">→</span></div>
                <div className="text-2xl font-extrabold" style={{ color }}>{after}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 sm:py-28 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-14"><p className="text-[10px] font-bold tracking-widest uppercase text-violet-600 dark:text-violet-400 mb-3">How It Works</p><h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4">From Repo to Production in Hours</h2><p className="text-base text-slate-500 dark:text-slate-400 font-light max-w-lg mx-auto">Four steps. No DevOps team. No YAML.</p></div>
          <div className="relative">
            <div className="hidden lg:block absolute top-10 left-[12.5%] right-[12.5%] h-px bg-gradient-to-r from-transparent via-slate-200 dark:via-slate-800 to-transparent" />
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {HOW_IT_WORKS.map(({ step, title, color, desc }) => (
                <div key={step} className="flex flex-col items-center text-center group">
                  <div className="w-20 h-20 rounded-2xl flex items-center justify-center mb-5 text-xl font-extrabold font-mono z-10 transition-all duration-300 group-hover:scale-110"
                    style={{ background: color + "12", color, border: `2px solid ${color}30` }}>{step}</div>
                  <h3 className="text-sm font-extrabold mb-2 tracking-tight">{title}</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 font-light leading-relaxed">{desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="py-20 px-4 sm:px-6 lg:px-8 border-y border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/40">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12"><p className="text-[10px] font-bold tracking-widest uppercase text-violet-600 dark:text-violet-400 mb-3">Customer Stories</p><h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">Teams Shipping Faster</h2></div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {TESTIMONIALS.map(({ quote, company, role, initial, color }) => (
              <div key={company} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-7 flex flex-col gap-5 relative overflow-hidden">
                <div className="absolute top-0 inset-x-0 h-0.5" style={{ background: `linear-gradient(90deg, ${color}, ${color}44)` }} />
                <div className="text-3xl font-serif text-slate-100 dark:text-slate-800">"</div>
                <p className="text-sm text-slate-600 dark:text-slate-300 font-light leading-relaxed flex-1">{quote}</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-extrabold text-sm flex-shrink-0" style={{ background: `linear-gradient(135deg, ${color}, ${color}cc)` }}>{initial}</div>
                  <div><div className="text-sm font-bold">{company}</div><div className="text-xs text-slate-400 mt-0.5">{role}</div></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-24 sm:py-32 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_60%_at_50%_50%,rgba(139,92,246,0.07),transparent)] dark:bg-[radial-gradient(ellipse_60%_60%_at_50%_50%,rgba(139,92,246,0.13),transparent)]" />
        <div className="relative max-w-2xl mx-auto text-center">
          <p className="text-[10px] font-bold tracking-widest uppercase text-violet-600 dark:text-violet-400 mb-6">Get Started</p>
          <h2 className="text-4xl sm:text-5xl font-extrabold tracking-tight leading-tight mb-6">Ready to ship faster?</h2>
          <p className="text-base text-slate-500 dark:text-slate-400 font-light leading-relaxed mb-10">Start your free trial. No credit card. No YAML. Production-ready CI/CD in under an hour.</p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Link href="https://console.quickinfra.cloud/" className="flex items-center gap-2 px-7 py-3.5 rounded-xl text-sm font-bold bg-violet-600 hover:bg-violet-500 text-white shadow-xl shadow-violet-600/25 transition-all hover:-translate-y-0.5">Start Free Trial <ArrowRight size={16} /></Link>
          </div>
          <p className="mt-6 text-[10px] font-bold tracking-widest uppercase text-slate-300 dark:text-slate-700">ISO/IEC 27001 · AWS Qualified Software · Zero YAML Guaranteed</p>
        </div>
      </section>

    </div>
  );
}